name: test
on:
  push:
  schedule:
    - cron: '0 21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install babashka
        run: bash <(curl -s https://raw.githubusercontent.com/borkdude/babashka/master/install)
      - run: bb --version
      - name: Build README
        env:
          README_TOKEN: ${{ secrets.README_TOKEN }}
        run: |
          make build
          cat README.adoc
