name: build
on:
  push:
  schedule:
    - cron: '0 21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install babashka
        run: |
          curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install
          chmod +x install
          ./install --dir $(pwd)
          ./bb --version
      - name: Build README
        env:
          README_TOKEN: ${{ secrets.README_TOKEN }}
        run: |
          ./bb build.clj run
          cat README.adoc
      - name: Commit and push if changed
        run: |
          git diff
          git config --global user.email "readme-bot@example.com"
          git config --global user.name "README-bot"
          git add -A
          git commit -m "Updated README" || exit 0
          git push
